[versions]
agp = "8.13.0"
androidx-activityCompose = "1.11.0"
androidx-annotation = "1.9.1"
androidx-core = "1.17.0"
androidx-browser = "1.9.0"
androidx-media = "1.8.0" # https://developer.android.com/jetpack/androidx/releases/media3
androidx-splashscreen = "1.0.1"
google-services = "4.4.4"
appcompat = "1.7.1" # https://developer.android.com/jetpack/androidx/releases/appcompat
compose-plugin = "1.9.2"
kotlin = "2.2.20"
kotlin-coroutines = "1.10.2"
kotlin-serialization-runtime = "1.9.0"
kotlin-datetime = "0.7.1" # https://github.com/Kotlin/kotlinx-datetime/releases
kotlin-immutable = "0.4.0"
kotlin-io = "0.8.0"
ksp = "2.3.0"
klibs-gradleplugin = "1.11.4" # https://github.com/makeevrserg/gradle-plugin# Exposed
decompose = "3.4.0"
# The update will break AssistedInject
# https://flipper.atlassian.net/browse/MOB-1948
metro = "0.6.8"
essenty = "2.5.0"
settings = "1.3.0"
markdown = "0.38.1" # https://github.com/mikepenz/multiplatform-markdown-renderer/releases
ktor = "3.3.1" # https://ktor.io/
timber = "5.0.1" # https://github.com/JakeWharton/timber/releases
timber-treessence = "1.2" # https://github.com/LionZXY/Treessence
detekt = "1.23.8" # https://detekt.dev/docs/gettingstarted/gradle/
buildkonfig = "5.7.1"
lifecycle = "2.9.4" # https://developer.android.com/jetpack/androidx/releases/lifecycle
compose-placeholder = "1.0.12"
androidx-compose = "1.9.4" # https://developer.android.com/jetpack/androidx/releases/compose-ui
# todo https://github.com/composablehorizons/compose-unstyled/issues/138
composables = "1.47.2" # https://github.com/composablehorizons/compose-unstyled
klibs-kstorage = "4.4.1" # https://github.com/makeevrserg/klibs.kstorage
room = "2.8.3" # https://developer.android.com/jetpack/androidx/releases/room
room-sqlite = "2.6.1"
accompanist = "0.37.3" # https://github.com/google/accompanist/releases
horologist = "0.7.15" # https://github.com/google/horologist/releases
wear = "1.3.0" # https://developer.android.com/jetpack/androidx/releases/wear
wear-gms = "19.0.0" # https://mvnrepository.com/artifact/com.google.android.gms/play-services-wearable?repo=google
wear-interaction-phone = "1.1.0" # https://developer.android.com/jetpack/androidx/releases/wear
wear-interaction-remote = "1.1.0" # https://developer.android.com/jetpack/androidx/releases/wear
wear-ongoing = "1.1.0"
compose-wear = "1.5.4" # https://developer.android.com/jetpack/androidx/releases/wear-compose
compose-wear-preview = "1.0.0" # https://mvnrepository.com/artifact/androidx.wear/wear-tooling-preview
haze = "1.6.10"
sentry-runtime = "8.25.0" # https://github.com/getsentry/sentry-java/releases
sentry-gradle = "5.12.2" # https://github.com/getsentry/sentry-android-gradle-plugin/releases
gms-time = "16.0.1" # https://developers.google.com/location-context/time
truetime = "4.0.2" # https://central.sonatype.com/artifact/uk.kulikov/truetime
encoding = "2.5.0"
encoding-hash = "0.8.0"
jna = "5.18.1"
jnativehook = "2.2.2"
jupiter = "6.0.1"
jtransforms = "3.1" # https://github.com/wendykierp/JTransforms
roboelectric = "4.16" # https://github.com/robolectric/robolectric/releases
androidx-test = "1.3.0"
ble = "2.0.0-alpha10"
mockk = "1.14.6" # https://mockk.io/
phoenix = "3.0.0"
fastutil = "8.5.18" # https://github.com/vigna/fastutil/tags
zip4j = "2.11.5" # https://github.com/srikanth-lingala/zip4j/releases
posthog = "3.25.0"
vaniktech = "0.34.0" #https://github.com/vanniktech/gradle-maven-publish-plugin

[libraries]
vaniktech = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "vaniktech" }
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-ksp-gradle = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
compose-multiplatform-gradle = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-plugin" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradle = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
klibs-kstorage = { module = "ru.astrainteractive.klibs:kstorage", version.ref = "klibs-kstorage" }

# Linters
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
metro-gradle = { module = "dev.zacsweers.metro:dev.zacsweers.metro.gradle.plugin", version.ref = "metro" }

decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-composeExtension = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }

kotlin-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlin-io" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization-runtime" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-datetime" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlin-immutable" }

# Testing
junit-bom = { module = "org.junit:junit-bom", version.ref = "jupiter" }
jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter" }
roboelectric = { module = "org.robolectric:robolectric", version.ref = "roboelectric" }
androidx-test = { module = "androidx.test.ext:junit", version.ref = "androidx-test" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "settings" }
settings-observable = { module = "com.russhwolf:multiplatform-settings-make-observable", version.ref = "settings" }
settings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "settings" }

# Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js-wasm-js", version.ref = "ktor" }
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
timber-tressence = { module = "uk.kulikov:treesense", version.ref = "timber-treessence" }
sentry = { module = "io.sentry:sentry-android", version.ref = "sentry-runtime" }
sentry-timber = { module = "io.sentry:sentry-android-timber", version.ref = "sentry-runtime" }
zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidx-compose" }

accompanist-drawable = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }

# wear
encoding-hash-md = { module = "org.kotlincrypto.hash:md", version.ref = "encoding-hash" }

# BLE

ble-client = { module = "no.nordicsemi.kotlin.ble:client-android", version.ref = "ble" }
ble-client-mock = { module = "no.nordicsemi.kotlin.ble:client-android-mock", version.ref = "ble" }
fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
buildkonfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildkonfig" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services" }
sentry = { id = "io.sentry.android.gradle", version.ref = "sentry-gradle" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }

# klibs - core
klibs-gradle-detekt = { id = "ru.astrainteractive.gradleplugin.detekt", version.ref = "klibs-gradleplugin" }
klibs-gradle-detekt-compose = { id = "ru.astrainteractive.gradleplugin.detekt.compose", version.ref = "klibs-gradleplugin" }
klibs-gradle-dokka-root = { id = "ru.astrainteractive.gradleplugin.dokka.root", version.ref = "klibs-gradleplugin" }
klibs-gradle-dokka-module = { id = "ru.astrainteractive.gradleplugin.dokka.module", version.ref = "klibs-gradleplugin" }
klibs-gradle-java-core = { id = "ru.astrainteractive.gradleplugin.java.core", version.ref = "klibs-gradleplugin" }
klibs-gradle-publication = { id = "ru.astrainteractive.gradleplugin.publication", version.ref = "klibs-gradleplugin" }
klibs-gradle-rootinfo = { id = "ru.astrainteractive.gradleplugin.root.info", version.ref = "klibs-gradleplugin" }
# klibs - android
klibs-gradle-android-core = { id = "ru.astrainteractive.gradleplugin.android.core", version.ref = "klibs-gradleplugin" }
klibs-gradle-android-compose = { id = "ru.astrainteractive.gradleplugin.android.compose", version.ref = "klibs-gradleplugin" }
klibs-gradle-android-apk-sign = { id = "ru.astrainteractive.gradleplugin.android.apk.sign", version.ref = "klibs-gradleplugin" }
klibs-gradle-android-apk-name = { id = "ru.astrainteractive.gradleplugin.android.apk.name", version.ref = "klibs-gradleplugin" }
klibs-gradle-android-namespace = { id = "ru.astrainteractive.gradleplugin.android.namespace", version.ref = "klibs-gradleplugin" }