name: "Tests"
on:
  workflow_call:

jobs:
  tests:
    strategy:
      matrix:
        target:
          - "allTests"
          - "macosX64Test"
          - "macosArm64Test"
          - "iosX64Test"
          - "jvmTest"
    name: "Run tests"
    runs-on: [ self-hosted, Linux ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Give gradle permission
        run: chmod +x gradlew
      - name: Run tests
        uses: gradle/gradle-build-action@v3
        with:
          arguments: ${{ matrix.target }} --stacktrace