name: "Release iOS XCFramework"

on:
  workflow_call:
    inputs:
      VERSION_NAME:
        required: true
        type: string
      VERSION_CODE:
        required: false
        type: string

jobs:
  publish_xcframework:
    name: "Publish XCFramework"
    runs-on: [ self-hosted, macOS ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Replace gradle properties with sed
        run: |
          sed -i -e 's/^makeevrserg.project.version.string=.*$/makeevrserg.project.version.string=${{ inputs.VERSION_NAME }}/g' gradle.properties
          sed -i -e 's/^makeevrserg.project.version.code=.*$/makeevrserg.project.version.code=${{ inputs.VERSION_CODE }}/g' gradle.properties
      - name: Build release xcframework zip
        id: files_release
        run: |
          ./gradlew :entrypoint:zipXCFrameworkRelease --stacktrace
          echo "file_release=entrypoint/build/xcframework-zips/BusyLibKMP-release.xcframework.zip" >> "$GITHUB_OUTPUT"
        env:
          ORG_GRADLE_PROJECT_current_flavor_type: PROD
      - name: Build debug xcframework zip
        id: files_debug
        run: |
          ./gradlew :entrypoint:zipXCFrameworkDebug --stacktrace
          echo "file_debug=entrypoint/build/xcframework-zips/BusyLibKMP-debug.xcframework.zip" >> "$GITHUB_OUTPUT"
        env:
          ORG_GRADLE_PROJECT_current_flavor_type: DEBUG
      - name: Publish release
        id: create_release
        uses: softprops/action-gh-release@e7a8f85e1c67a31e6ed99a94b41bd0b71bbee6b8 # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ steps.files_release.outputs.file_release }}
            ${{ steps.files_debug.outputs.file_debug }}
          tag_name: ${{ inputs.VERSION_NAME }}
          name: BUSY Lib ${{ inputs.VERSION_NAME }}
          draft: false
          prerelease: false
