name: "gradle-wrapper-validation"
on:
  workflow_call:

jobs:
  validation:
    name: "Gradle Wrapper Validation"
    runs-on: [ self-hosted, Linux ]
    steps:
      - uses: actions/checkout@v5
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3